FROM python:3.9.9-slim-buster

COPY scripts/setup_minio.py /scripts/setup_minio.py
COPY services/minio /services/minio

RUN pip install minio

COPY scripts/wait-for-it.sh /scripts/wait-for-it.sh
RUN chmod +x /scripts/wait-for-it.sh

CMD ["/scripts/wait-for-it.sh", "minio:9000", "--", "python", "/scripts/setup_minio.py"]