apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out kube
    kompose.version: 1.31.2 (HEAD)
  labels:
    io.kompose.service: api
  name: api
  namespace: vectorflow
spec:
  type: LoadBalancer
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
