apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out kube
    kompose.version: 1.31.2 (HEAD)
  labels:
    io.kompose.service: minio
  name: minio
spec:
  type: LoadBalancer
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: "9001"
      port: 9001
      targetPort: 9001
      protocol: TCP
  selector:
    io.kompose.service: minio
status:
  loadBalancer: {}
