apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out kube
    kompose.version: 1.31.2 (HEAD)
  labels:
    io.kompose.service: vdb-upload-worker
  name: vdb-upload-worker
  namespace: vectorflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vdb-upload-worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out kube
        kompose.version: 1.31.2 (HEAD)
      labels:
        io.kompose.network/vectorflow: "true"
        io.kompose.service: vdb-upload-worker
    spec:
      containers:
        - args:
            - bash
            - /wait-for-it.sh
            - rabbitmq:5672
            - --
            - python
            - vdb_upload_worker.py
          env:
            - name: VDB_UPLOAD_QUEUE
              valueFrom:
                configMapKeyRef:
                  key: VDB_UPLOAD_QUEUE
                  name: config-map
            - name: LOCAL_VECTOR_DB
              valueFrom:
                configMapKeyRef:
                  key: LOCAL_VECTOR_DB
                  name: config-map
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: config-map
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: config-map
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: config-map
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USERNAME
                  name: config-map
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_HOST
                  name: config-map
            - name: RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_PASSWORD
                  name: config-map
            - name: RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_USERNAME
                  name: config-map
          image: vectorflow_vdb_upload_worker
          name: vdb-upload-worker
          imagePullPolicy: IfNotPresent
          resources: {}
      restartPolicy: Always
status: {}
