MAX_THREADS_OPENAI = 20
MAX_OPENAI_EMBEDDING_BATCH_SIZE = 2048
PINECONE_BATCH_SIZE = 128
SLEEP_SECONDS = 5
PIKA_RETRY_INTERVAL = 10
HUGGING_FACE_BATCH_SIZE = 32
VALIDATION_TIMEOUT = 30
MAX_BATCH_RETRIES = 3