from enum import Enum

class BatchStatus(Enum):
    NOT_STARTED = 'NOT_STARTED'
    CALCULATING_EMBEDDINGS = 'CALCULATING_EMBEDDINGS'
    EMBEDDING_COMPLETE = 'EMBEDDING_COMPLETE'
    VDB_UPLOAD = 'VDB_UPLOAD'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'