
name: Vectorflow_Unittests

on:
  pull_request:
    branches: [ "main" ]
    types: ["opened", "reopened", "edited"]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    env:
      #INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}
      #OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY }}
      #QDRANT_KEY: ${{ secrets.QDRANT_KEY }}
      LOCAL_VECTOR_DB: ${{ secrets.LOCAL_VECTOR_DB }}
      
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies - Api
        run: |
          python -m pip install --upgrade pip
          pip install -r src/api/requirements.txt

      - name: Run Api unittests
        run: |
          cd src
          python -m unittest api.tests.test_app

      - name: Install depencies - Worker
        run: |
          python -m pip install --upgrade pip
          pip install -r src/worker/requirements.txt

      - name: Run Worker/Vdb_worker unittests
        run: |
          cd src
          python -m unittest worker.tests.test_worker
          python -m unittest worker.tests.test_vdb_upload_worker

      
